### ISSUE TITLE
Issue with iOS, link doesn't open the NS app

### ISSUE THREAD

**Issue by rrr3da** [sebestindragos/nativescript-plugin-universal-links#4]
Dear @sebestindragos thank you for this plugin.

I'm building a nativescript-vue app and I can get it work for Android.
I can't get it work with iOS btw...

The AASA.json file is served correctly as a text/json file and contains one entry:
```
        "appID": "TEAMID.BUNDLEIDENTIFIER",
        "paths": [ "/*", "*"]
```
In fact, we need to hit URLs like https://www.mydomain.xyz/*

Before launching with "tns run ios" I do clear the build by removing platforms/ios to be sure everything is loaded from scratch.
After the app is prepared, platforms/ios/_appname_/_appname_.entitlements file contains the links to be parsed under the Signing & Capabilities tab.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.developer.associated-domains</key>
    <array>
      <string>applinks:*.mydomain.xyz</string>
      <string>applinks:mydomain.xyz</string>
    </array>
  </dict>
</plist>
```

The DEVELOPMENT_TEAM key is set in build.xcconfig, too.

It doesn't work from any iOS emulator, neither from a real iPhone

Glad if you can help me, regards

**Comment by sebestindragos** [comment]
Hi, @rrr3da ! How are you testing the universal link trigger? Also, please drop the link to your AASA.json file here, I'll take a look at it. Please note that the file is only required on IOS, the Android version will work even if that file doesn't exist.

**Comment by rrr3da** [comment]
yes, sorry I just updated the desc a few minutes ago!
i'm currently having a look at [this](https://blog.branch.io/what-is-an-aasa-apple-app-site-association-file/) guide, I'm fixing a couple of things and I'll let you know

if that works, it would be nice to improve the library readme. let you know ;)

**Comment by rrr3da** [comment]
Ok @sebestindragos, I got it working for iOS!

In my case, I was serving the AASA file as https://mydomain/apple-app-site-association.json, but I had to remove the .json extension and to set Content-Type="application/json" to the response headers.

I'm closing the issue, regards!

**Comment by sebestindragos** [comment]
@rrr3da glad you figured it out.
