### ISSUE TITLE
Universal links are not loaded

### ISSUE THREAD

**Issue by MitkoTschimev** [sebestindragos/nativescript-plugin-universal-links#5]
Hey guys, 

I am fighting for days with the setup but somehow it is not working.

What I have done:

1. serve the apple-app-site-association via `https://www.visual-knight.io/.well-known/apple-app-site-association`
-> here already the [appsearch-validation-tool](https://search.developer.apple.com/appsearch-validation-tool) shows the json is not parsable but I can't see any error

2. I added the *appname.entitlements* file to */appname/App_Resources/iOS/tipyourheronativescript.entitlements*

I also checked the swcutil_show.txt
```
--------------------------------------------------------------------------------
Service:              applinks
App ID:               6YKDAH9HN4.org.dev-thought.tipyourhero
App Version:          1.0.9
Domain:               visual-knight.io
User Approval:        unspecified
Site/Fmwk Approval:   unspecified
Flags:                
Next Check:           0001-01-01 03:33:39 +0000
```
I can not find any patterns so I guess the app is not able to load the apple-app-site-association or the nativescript setup is wrong.

But I can not find any mistake... :(
I hope you guys can help me

Cheers

**Comment by sebestindragos** [comment]
Hi @MitkoTschimev 

Did you manage to get this working? Sorry for the delayed response, I didn't get an email when you opened the issue.

**Comment by MitkoTschimev** [comment]
It was a misconfiguration by the server ;) 

But at the end I decided to go for fire base dynamic links and other features because they are free and compatible with nice fallbacks.
