### ISSUE TITLE
Execution on "cold" startup

### ISSUE THREAD

**Issue by leganz** [sebestindragos/nativescript-plugin-universal-links#7]
Hi thx for sharing this wonderful plugin with us.
It is pretty neat but currenlty I run into a single issue I was not capable of resolving yet. Mabye you have an idea where to start.

I use a nfc tag with a custom schema e.g myapp://test
The android device is able to resolve that and open the app.
Now I have on problem:
When the app was already started the registerUniversalLinkCallback will be executed like it should
If the app is started "fresh" this callback somehow never get triggered. 
I placed the registerUniversalLinkCallback in the app component of the nativescript app.

**Comment by sebestindragos** [comment]
Hi @leganz ,

Sorry, but I don't have any experience with multiple url handlers. If you do find a fix, feel free to make a PR :)

**Comment by leganz** [comment]
I found a way arround that issue - might be helpful for others.
I check in the ngViewAfterInit if there is an entry... not perfect but it solves my issue.
Thx anyway :-)

**Comment by fpaaske** [comment]
I don't think this issue should be closed.

I have the same problem; if that app is already running in the background everything works fine. But if app is closed and not running, the callback is never called.

But I can confirm @leganz's workaround works.

Also, I tested [another plugin](https://github.com/hypery2k/nativescript-urlhandler) too, but there is another [bug](https://github.com/hypery2k/nativescript-urlhandler/issues/91); the callback is called on every resume of the app as well.
