### ISSUE TITLE
NativeScript 7 Support

### ISSUE THREAD

**Issue by asharghi** [sebestindragos/nativescript-plugin-universal-links#8]
Hi @sebestindragos. Thanks for your great work on this plugin. Are you planing on supporting NS7 soon? If you need any help, nStudio is helping plugin authors with it https://nativescript.org/blog/nativescript-7-compatible-plugins/

**Comment by sebestindragos** [comment]
Waiting for [#9](https://github.com/sebestindragos/nativescript-plugin-universal-links/pull/9). I don't have time right now to test for NS7, my internal project is staying on NS6 for the time being.

**Comment by asharghi** [comment]
I'm planning to migrate my app to NS7 in a few monts, and can verify then. But may I suggest to publish a major version release of Nathans pr? So you'll have version 1 for NS6 and version 2 for NS7, then if there are any problems with the PR it can later be fixed as patches and minor releases.

**Comment by ReeceReynolds** [comment]
Following. Also interested in this being updated to support NS 7.

**Comment by sebestindragos** [comment]
Hi guys, just published `nativescript-plugin-universal-links@2.0.0` with support for NS7. Let me know if it works for you.
And a huge thanks to @NathanWalker , it was his PR that added support for NS7.

**Comment by liuy97** [comment]
I got an uncaught  exception using nativescript-plugin-universal-links@2.0.0 in iOS.

`
CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
../node_modules/nativescript-plugin-universal-links/plugin-universal-links.js(file: node_modules/nativescript-plugin-universal-links/plugin-universal-links.ios.js:7:0)`

**Comment by NathanWalker** [comment]
@sebestindragos You most likely forgot to `ts-patch install` in your `src` before building. If can do that and republish a patch would fix that ^ - always check your compiled .js files to make sure the transformations took place as the compiled .js should have no mention of `NativeClass` anywhere.

**Comment by NathanWalker** [comment]
This is another reason we highly recommend the plugin workspaces as it handles things like that all seamlessly.:
https://github.com/NativeScript/plugin-seed
https://nativescript.org/blog/announcing-plugin-workspaces/

**Comment by tralves** [comment]
While this package is not re-published, you can use my fork in `package.json` like this:
```
"nativescript-plugin-universal-links": "https://github.com/tralves/nativescript-plugin-universal-links/raw/master/dist/nativescript-plugin-universal-links.tar.gz",
```

**Comment by sebestindragos** [comment]
This project is no longer maintained in this repo, it has been taken over by the NS Community
https://github.com/nativescript-community/universal-links
